- name: backend server
  hosts: backend
  become: yes
  tasks:
  - name: disbale package
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable package
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install package
    ansible.builtin.package:
      name: nodejs
      state: present

  

